### ISSUE TITLE
缺少空格吗？

### ISSUE THREAD

**Issue by vmtest888** [DeronW/minify-font#2]
游戏找不到空格，crash了

**Comment by delong8** [comment]
> 游戏找不到空格，crash了

“空格” 本身不可见，所以简化字体里没有包含空格，简化字体中只有 3500 常用字，如果遇到生僻字，也会出跟空格一样的问题

**Comment by vmtest888** [comment]
单机游戏字符可控。  我加了空格编译后可以正常运行的。  
（因为游戏在计算字符宽度的时候找不到空格，触发了除0异常。）

**Comment by vmtest888** [comment]
还是建议大佬能加上空格。哈哈哈。

**Comment by delong8** [comment]
加上空格了

**Comment by vmtest888** [comment]
浏览器可能会降级处理，我用的某个开源游戏引擎直接crash了。
谢谢大佬。
